### ISSUE TITLE
does compton's color inversion work with your fork of notion?

### ISSUE THREAD

**Issue by anderspapitto** [neg-serg/dotfiles#1]
Hello! I want to get color inversion working with notion, and I found your fork with this commit https://github.com/neg-serg/notion/commit/6d77ac848099f344f80bededb436c13d2cb8c743.

Does that commit enable the color-inversion of compton to work correctly?

Also, should it be safe to cherry-pick the commit onto the upstream master?

**Comment by neg-serg** [comment]
>I want to get color inversion working with notion
I don't know anything about color-inverse. What is it?

That fix is about a root window handling, not the compositing support itself. Compositing support still not so perfect as it could be. And maybe it cannot be fixed at all by anyone. I've spend pretty long time trying to hack some parts of ion3/notion, but with no success.

>Also, should it be safe to cherry-pick the commit onto the upstream master?

I don't know the state of the current Notion wm codebase. Anyway you may try to apply this patch to the upstream, personally I don't interested in notion wm support in any form anymore.

For now I've migrated to i3 with this following scripts:
https://github.com/neg-serg/negi3mods
Which is the "port" of my favorite features as named scratchpad, better run-or-raise, etc to the i3 wm via i3ipc.

Why you are still using notion for now?.

**Comment by anderspapitto** [comment]
ok, thanks for the answer

I meant the invert-color-include option, documented here http://manpages.ubuntu.com/manpages/trusty/man1/compton.1.html

It doesn't work with notion because it ends up inverting the root window instead of the individual windows.

I actually have been using i3, but I was looking at other options because I want to have static tiling instead of dynamic. Maybe it's easier to build it with scripts on top of i3.

**Comment by neg-serg** [comment]
>It doesn't work with notion because it ends up inverting the root window instead of the individual windows.

I don't try it, but there is a lot of chance that I've fixed it with this patch, because of it's about root window / virtual root handling.

>I was looking at other options because I want to have static tiling instead of dynamic

What do you mean? i3 already has static tiling. The dynamic part is only per-frame tiling. For example you can have two tabbed frames with vertical splitting of screen space, etc. But you can create several frames with several levels because of binary-tree windows representation in i3 wm. It is true that there is no placeholders in i3, but in general tiling system very similar to notion/stumpwm..

Also there is a session manager inside i3. Personally I'm not using it., because most of time use only fullscreen windows + scrachpads.

If you have some ideas how to improve i3 UX you are welcome.)

**Comment by anderspapitto** [comment]
yeah basically I want placeholders :)

anyway thanks for all the answers, that saved me some time.
